const carbonData = {
  // Paises con carbono positivos
  'United States of America': { 
    status: 'POSITIVO', 
    color: '#ff3333', 
    descHover: 'Alta emisión industrial.', // Para el cuadrito al pasar el mouse
    descGeneral: 'Estados Unidos es uno de los mayores emisores históricos debido a su alta industrialización, dependencia del automóvil y consumo energético per cápita.', // Para la caja 1
    prediccion: 'Si no se reducen drásticamente las emisiones, se enfrentarán a sequías más extremas, huracanes devastadores y pérdida de costas.',
    prediccionExtendida: 'Si Estados Unidos no acelera la reducción de emisiones, se proyecta un aumento significativo en la frecuencia e intensidad de eventos climáticos extremos hacia mediados y finales de siglo. Esto incluye sequías más prolongadas en el oeste, huracanes más intensos en el Atlántico y Golfo de México, aumento del nivel del mar que amenaza zonas costeras densamente pobladas, y mayores olas de calor.',
    medidas: 'Están implementando leyes masivas para subsidiar la energía solar, eólica y la adopción de vehículos eléctricos.',
    medidasExtendida: 'Estados Unidos ha aprobado políticas climáticas de gran escala, incluyendo subsidios e incentivos para energía solar, eólica, almacenamiento en baterías y vehículos eléctricos, así como normas más estrictas de eficiencia energética. También se están desarrollando proyectos de captura y almacenamiento de carbono y modernización de la red eléctrica. Sin embargo, el país aún mantiene una producción significativa de petróleo y gas, por lo que el impacto neto dependerá de la rapidez con que las energías limpias sustituyan a los combustibles fósiles.',
    imgDefecto: 'https://elordenmundial.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2017/01/7I0fP5W-1024x640.jpg.webp',
    imgCatastrofe: 'https://www.lavanguardia.com/files/article_main_microformat/uploads/2020/01/22/5fa903701cf8a.jpeg',
    imgEcologia: 'https://cdn.elperiodicodelaenergia.com/2024/08/66c76ac1d6403065673820d1.jpg'
  },
    'China': {
    status: 'POSITIVO',
    color: '#ff3333',
    descHover: 'Mayor emisor global de CO₂.',
    descGeneral: 'China es el mayor emisor de CO₂ del mundo debido a su enorme sector industrial y dependencia histórica del carbón, aunque lidera inversiones en energías renovables.',
    prediccion: 'Si no acelera la transición energética, seguirá siendo el principal contribuyente al aumento global de emisiones.',
    prediccionExtendida: 'De mantenerse las tendencias actuales de crecimiento industrial y consumo energético, las emisiones totales de China seguirían siendo muy altas en las próximas décadas. Aunque el país está expandiendo renovables rápidamente, la demanda eléctrica y el uso de carbón aún son significativos. Sin cambios estructurales más profundos en la matriz energética y eficiencia industrial, es probable que continúe siendo uno de los principales emisores hacia 2075.',
    medidas: 'Expansión masiva de energía solar y eólica y meta de neutralidad de carbono para 2060.',
    medidasExtendida: 'China está desplegando a gran escala energía solar, eólica y almacenamiento, además de electrificación del transporte y desarrollo de mercados nacionales de carbono. También impulsa modernización industrial y eficiencia energética. Sin embargo, aún mantiene nuevas plantas de carbón para seguridad energética, lo que modera la velocidad de reducción neta.',
    imgDefecto: 'https://images.unsplash.com/photo-1683712988284-eba2c588c0eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Q2hpbmElMjAlRjAlOUYlODclQTglRjAlOUYlODclQjN8ZW58MHx8MHx8fDA%3D',
    imgCatastrofe: 'https://www.laizquierdadiario.com/IMG/arton29544.jpg',
    imgEcologia: 'https://i.blogs.es/2c8924/aschina-paneles-solares/1200_800.jpeg'
  },
    'Russia': {
    status: 'POSITIVO',
    color: '#ff3333',
    descHover: 'Gran emisor por combustibles fósiles.',
    descGeneral: 'Rusia depende fuertemente del gas y petróleo, lo que mantiene sus emisiones elevadas pese a su gran cobertura forestal.',
    prediccion: 'Sin cambios estructurales, las emisiones se mantendrán altas por su economía energética.',
    prediccionExtendida: 'Si Rusia mantiene su modelo económico basado en exportaciones de combustibles fósiles, es probable que las emisiones se mantengan relativamente altas a largo plazo. Aunque sus bosques absorben carbono, el crecimiento del sector energético podría compensar ese beneficio. Cambios significativos dependerán de diversificación económica y modernización tecnológica.',
    medidas: 'Programas limitados de eficiencia energética y compromisos climáticos moderados.',
    medidasExtendida: 'El país ha anunciado objetivos de reducción de emisiones y mejoras de eficiencia energética, además de cierto monitoreo forestal. No obstante, la expansión de renovables es más lenta que en otras economías grandes y la dependencia de hidrocarburos sigue siendo dominante en su estrategia energética.',
    imgCatastrofe: 'https://ceipaz.org/wp-content/uploads/2021/01/foto-bosque.jpg',
    imgEcologia: 'https://mf.b37mrtl.ru/rbthmedia/images/2020.11/article/5fbf46f985600a1d0a3ca818.jpg'
  },
  'United Kingdom': {
    status: 'NEUTRAL',
    color: '#ffcc00',
    descHover: 'Emisiones en fuerte descenso.',
    descGeneral: 'El Reino Unido ha reducido significativamente sus emisiones desde 1990 gracias al abandono del carbón y expansión de renovables.',
    prediccion: 'Podría alcanzar la neutralidad si mantiene el ritmo de descarbonización.',
    prediccionExtendida: 'Si continúa la eliminación de combustibles fósiles y la electrificación del transporte y calefacción, el Reino Unido tiene alta probabilidad de alcanzar emisiones netas cercanas a cero antes de mediados de siglo. El principal reto será la descarbonización de edificios, aviación y sectores industriales difíciles de electrificar.',
    medidas: 'Meta legal de cero emisiones netas para 2050 y expansión de energía eólica marina.',
    medidasExtendida: 'El Reino Unido cuenta con una meta legal de net-zero para 2050, amplia capacidad eólica marina, sistemas de comercio de emisiones y programas de eficiencia energética en edificios. También impulsa captura y almacenamiento de carbono (CCS) y la electrificación del parque automotor.',
    imgDefecto: 'https://www.ecoportal.net/wp-content/uploads/2019/06/emisiones-de-carbono.jpg',
    imgCatastrofe: 'https://www.ecoportal.net/wp-content/uploads/2019/06/emisiones-de-carbono.jpg',
    imgEcologia: 'https://static.tvn-2.com/clip/adb43eb3-b956-42f1-96cc-efb556d3cca1_16-9-aspect-ratio_default_0.webp'
  },

  'France': {
    status: 'NEUTRAL',
    color: '#ffcc00',
    descHover: 'Bajas emisiones por energía nuclear.',
    descGeneral: 'Francia mantiene emisiones relativamente bajas en Europa debido a su alta dependencia de la energía nuclear.',
    prediccion: 'Se mantendría cerca de la neutralidad si conserva su matriz baja en carbono.',
    prediccionExtendida: 'Mientras Francia mantenga su fuerte base nuclear y continúe expandiendo renovables, es probable que sus emisiones permanezcan relativamente bajas. Los desafíos principales están en el transporte, la calefacción de edificios y la renovación del parque nuclear envejecido.',
    medidas: 'Políticas de transición energética y mantenimiento del parque nuclear.',
    medidasExtendida: 'Francia impulsa la modernización de reactores nucleares, expansión de energía eólica y solar, electrificación del transporte y mejoras de eficiencia energética. También aplica impuestos al carbono en ciertos sectores y programas de rehabilitación térmica de viviendas.',
    imgDefecto: 'https://fotografias.lasexta.com/clipping/cmsimages02/2022/11/30/32369DA7-1240-4E22-ACCA-06B1F698343C/baguette-francesa-declarada-patrimonio-inmaterial-unesco_104.jpg?',
    imgCatastrofe: 'https://s.france24.com/media/display/81151f42-9c1c-11e9-bef3-005056a98db9/francia_pollution.jpg',
    imgEcologia: 'https://i.blogs.es/9f3b08/edf-ap2/500_333.jpeg'
  },

  'Germany': {
    status: 'POSITIVO',
    color: '#ff3333',
    descHover: 'Alta emisión industrial en transición.',
    descGeneral: 'Alemania es un gran emisor europeo por su industria, aunque está en plena transición energética (Energiewende).',
    prediccion: 'Las emisiones bajarán, pero seguirán siendo significativas sin acelerar la descarbonización.',
    prediccionExtendida: 'Si Alemania mantiene su ritmo actual de transición energética, las emisiones continuarán disminuyendo gradualmente. Sin embargo, sectores como la industria pesada y el transporte podrían ralentizar la reducción. La eliminación completa del carbón y la expansión del hidrógeno verde serán determinantes hacia 2050-2075.',
    medidas: 'Expansión renovable y eliminación progresiva del carbón.',
    medidasExtendida: 'Alemania impulsa la Energiewende con gran inversión en eólica y solar, cierre progresivo de plantas de carbón, electrificación del transporte y desarrollo de hidrógeno verde para la industria. También aplica precios al carbono y programas de eficiencia energética.',
    imgDefecto: 'https://cypes.grupoeurohispana.com/img/articulos_facebook/ALEMANIA.jpg',
    imgCatastrofe: 'https://totalnewsagency.com/wp-content/uploads/2021/08/alemania-propuso-formar-una-alianza-internacional-contra-el-cambio-climatico-1.jpg',
    imgEcologia: 'https://www.gob.mx/cms/uploads/article/main_image/141306/Energiewende.jpg'
  },

  'Brazil': {
    status: 'POSITIVO',
    color: '#ff3333',
    descHover: 'Emisiones ligadas a deforestación.',
    descGeneral: 'Brasil tiene emisiones moderadas energéticas, pero la deforestación del Amazonas eleva su impacto climático.',
    prediccion: 'Podría empeorar si continúa la deforestación.',
    prediccionExtendida: 'El futuro climático de Brasil depende en gran medida del control de la deforestación amazónica. Si logra reducir la pérdida de bosques, podría disminuir notablemente su balance neto. En cambio, una expansión agrícola sin control aumentaría sus emisiones en las próximas décadas.',
    medidas: 'Programas de control de deforestación y expansión de energías limpias.',
    medidasExtendida: 'Brasil combina una matriz eléctrica relativamente limpia con políticas de monitoreo satelital de la Amazonía, programas contra la tala ilegal y compromisos climáticos internacionales. También promueve biocombustibles y expansión de energía eólica y solar.',
    imgDefecto: 'https://humanidades.com/wp-content/uploads/2017/04/brasil-1-e1566159470787.jpg',
    imgCatastrofe: 'https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2009/11/13/1258072302203/Deforestation-in-Novo--Pr-001.jpg?width=465&dpr=1&s=none&crop=none',
    imgEcologia: 'https://images.fastcompany.com/image/upload/f_webp,q_auto,c_fit,w_1024,h_1024/wp-cms/uploads/2017/10/7-heres-a-look-behind-the-largest-tropica-reforestation-projec.jpg'
  },

  'Saudi Arabia': {
    status: 'POSITIVO',
    color: '#ff3333',
    descHover: 'Alta huella por petróleo.',
    descGeneral: 'Economía altamente dependiente del petróleo con una de las mayores emisiones per cápita.',
    prediccion: 'Seguirá siendo alta sin diversificación energética.',
    prediccionExtendida: 'Si la economía saudí continúa centrada en hidrocarburos, las emisiones per cápita seguirán siendo elevadas. La transición dependerá de la velocidad de diversificación energética y del despliegue de tecnologías de captura de carbono.',
    medidas: 'Planes de energía solar dentro de Vision 2030.',
    medidasExtendida: 'El país impulsa proyectos solares y de hidrógeno, eficiencia energética y captura y almacenamiento de carbono (CCS). No obstante, el petróleo y gas siguen siendo el núcleo económico, por lo que la reducción neta dependerá de la escala real de implementación.',
    imgDefecto: 'https://res.cloudinary.com/ddjuftfy2/image/upload/f_webp,c_fill,q_auto,w_500/memphis/xlarge/7021af02a45444fb0dd65aae34f21fe8.jpg',
    imgCatastrofe: 'https://greentology.life/wp-content/uploads/2021/03/19072021_Arabia-Saudita-presenta-plan-verde-para-reducir-emisiones.png',
    imgEcologia: 'https://s03.s3c.es/imag/_v0/665x400/9/d/3/panel-solar-arabia.jpg',
  },

  'Bhutan': {
    status: 'NEGATIVO',
    color: '#00cc66',
    descHover: 'País carbono negativo.',
    descGeneral: 'Bhutan absorbe más CO₂ del que emite gracias a su extensa cobertura forestal y uso de energía hidroeléctrica.',
    prediccion: 'Probablemente se mantenga carbono negativo si conserva sus bosques.',
    prediccion: 'Probablemente se mantenga carbono negativo si conserva sus bosques.',
    prediccionExtendida: 'Bhutan tiene altas probabilidades de seguir siendo carbono negativo mientras mantenga su estricta protección forestal y su matriz hidroeléctrica. El riesgo principal proviene de urbanización futura y aumento del transporte motorizado.',
    medidas: 'Constitución exige mantener al menos 60% del territorio forestado.',
    medidasExtendida: 'Bhutan protege legalmente sus bosques, exporta energía hidroeléctrica limpia y promueve turismo sostenible. También desarrolla movilidad eléctrica y políticas de conservación de biodiversidad para mantener su balance climático positivo.',
    imgCatastrofe: 'https://static.nationalgeographicla.com/files/styles/image_3200/public/marcuswestbergbhutan-8.jpg',
    imgEcologia: 'https://previews.123rf.com/images/langdu8x/langdu8x1709/langdu8x170900511/90223206-rice-field-with-pine-forest-in-bhutan-bhutan-is-a-small-country-in-the-himalayas-between-the-tibet.jpg',
  },

  'Suriname': {
    status: 'NEGATIVO',
    color: '#00cc66',
    descHover: 'Amplios bosques tropicales.',
    descGeneral: 'Surinam es carbono negativo debido a su enorme cobertura forestal y baja industrialización.',
    prediccion: 'Seguirá siendo negativo si controla la explotación forestal.',
    prediccionExtendida: 'El país probablemente mantendrá su condición negativa si conserva sus bosques amazónicos. Sin embargo, la expansión petrolera o minera podría cambiar el balance en el largo plazo.',
    medidas: 'Protección de selvas y compromisos climáticos internacionales.',
    medidasExtendida: 'Surinam participa en iniciativas REDD+, conservación forestal y monitoreo ambiental. También explora desarrollo económico con menor impacto, aunque enfrenta presión por explotación de recursos naturales.',
    imgDefecto: 'https://media.istockphoto.com/id/1927599210/es/foto/paramaribo-surinam.jpg?s=612x612&w=0&k=20&c=0gNr1_4auIS7GwTsL5wI_L6TP_P5obaR4PzCPbwjboE=',
    imgCatastrofe: 'https://www.bothends.org/uploaded_files/mediaitem/deforestation.png',
    imgEcologia: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKjnZwkjyQfAKSu0sFmfxFhz53mDAbXrsw1Q&s',
  },

  'Panama': {
    status: 'NEGATIVO',
    color: '#00cc66',
    descHover: 'Uno de los pocos países carbono negativo.',
    descGeneral: 'Panamá mantiene balance negativo gracias a sus bosques tropicales y matriz energética relativamente limpia.',
    prediccion: 'Podría aumentar si crecen el transporte y la urbanización.',
    prediccionExtendida: 'Si el crecimiento urbano y del parque vehicular continúa al ritmo actual, las emisiones podrían aumentar en las próximas décadas. No obstante, la protección forestal y la transición energética podrían estabilizar el balance si se fortalecen las políticas climáticas.',
    medidas: 'Estrategia nacional de carbono neutralidad y protección forestal.',
    medidasExtendida: 'Panamá impulsa su Estrategia Nacional de Carbono Neutralidad, programas de reforestación, expansión de energías renovables y movilidad eléctrica. También mantiene áreas protegidas extensas que funcionan como sumideros naturales.',
    imgDefecto: 'https://www.revistainversionesynegocios.com/wp-content/uploads/2025/11/untitled-design-2022-11-02t160830516.jpg',
    imgCatastrofe: 'https://destinopanama.com.pa/wp-content/uploads/2024/01/UrbanixacionEstudio.jpg',
    imgEcologia: 'https://archivo.prensa-latina.cu/wp-content/uploads/2022/02/energia-renovables-Small.jpg',
  },

  'Gabon': {
    status: 'NEGATIVO',
    color: '#00cc66',
    descHover: 'Gran sumidero forestal.',
    descGeneral: 'Gabón absorbe más CO₂ del que emite debido a que más del 80% del país está cubierto por bosques.',
    prediccion: 'Se mantendrá negativo si continúa la protección forestal.',
    prediccionExtendida: 'Gabón tiene altas probabilidades de seguir siendo carbono negativo mientras mantenga sus selvas intactas. El riesgo principal es la expansión petrolera y maderera.',
    medidas: 'Políticas de conservación y mercado de créditos de carbono.',
    medidasExtendida: 'El país protege grandes áreas de selva, participa en mercados de carbono y promueve manejo forestal sostenible. También busca diversificar su economía para reducir la presión sobre los recursos naturales.',
    imgDefecto: 'https://sostenibilidadhn.wordpress.com/wp-content/uploads/2019/11/gabon.jpg',
    imgCatastrofe: 'https://www.independent.co.ug/wp-content/uploads/2019/05/Forests-degraded.jpg',
    imgEcologia: 'https://static.eldiario.es/clip/99353965-55c2-446f-92cb-3ee05183f544_16-9-aspect-ratio_default_0.jpg',
  },

  'Costa Rica': {
    status: 'NEUTRAL',
    color: '#ffcc00',
    descHover: 'Líder en energías renovables.',
    descGeneral: 'Costa Rica produce la mayor parte de su electricidad con renovables, manteniendo emisiones relativamente bajas.',
    prediccion: 'Podría alcanzar carbono neutralidad en próximas décadas.',
    prediccionExtendida: 'Si Costa Rica continúa electrificando transporte y manteniendo su matriz renovable, es probable que alcance emisiones netas muy bajas. El principal desafío es el sector transporte y el crecimiento urbano.',
    medidas: 'Plan Nacional de Descarbonización.',
    medidasExtendida: 'El país impulsa electrificación del transporte público, protección forestal, impuestos al carbono y expansión continua de energías renovables. También promueve ciudades sostenibles y eficiencia energética.',
    imgDefecto: 'https://www.civitatis.com/f/costa-rica/san-jose/san-jose-m.jpg',
    imgCatastrofe: 'https://www.revistaeyn.com/binrepository/775x451/0c0/0d0/none/26086/DDDX/huella-carbono-emision_2666187_20221012104649.jpg',
    imgEcologia: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoqZJYRJMijt1KbPEMZXh_9a-DdrgSPdlXfQ&s',
  },

  'Uruguay': {
    status: 'NEUTRAL',
    color: '#ffcc00',
    descHover: 'Matriz eléctrica muy limpia.',
    descGeneral: 'Uruguay genera la mayoría de su electricidad con fuentes renovables, reduciendo su intensidad de carbono.',
    prediccion: 'Podría acercarse a la neutralidad si electrifica transporte.',
    prediccionExtendida: 'Uruguay tiene buen posicionamiento para reducir aún más sus emisiones si avanza en movilidad eléctrica y eficiencia industrial. El crecimiento agrícola podría influir en sus emisiones futuras.',
    medidas: 'Fuerte inversión en eólica y solar.',
    medidasExtendida: 'Uruguay ha transformado su matriz eléctrica hacia renovables, impulsa hidrógeno verde, movilidad eléctrica y políticas de eficiencia energética, manteniendo una de las matrices más limpias de la región.',
    imgDefecto: 'https://19499770.fs1.hubspotusercontent-na1.net/hubfs/19499770/Punta%20Del%20Este%2C%20Uruguay.jpg',
    imgCatastrofe: 'https://latam-green.com/wp-content/uploads/2022/01/Uruguay-210122-a.jpeg',
    imgEcologia: 'https://www.energiaestrategica.com/wp-content/uploads/2021/09/uruguay-complementariedad-eolica-solar.jpg',
  },

  'Iceland': {
    status: 'NEUTRAL',
    color: '#ffcc00',
    descHover: 'Energía casi totalmente renovable.',
    descGeneral: 'Islandia usa principalmente energía geotérmica e hidroeléctrica, con bajas emisiones energéticas.',
    prediccion: 'Podría ser carbono neutral con captura de carbono.',
    prediccionExtendida: 'Islandia podría alcanzar emisiones netas muy bajas si amplía la captura directa de aire y electrifica completamente transporte y pesca. Su pequeña población facilita la transición.',
    medidas: 'Proyectos de captura y almacenamiento de CO₂.',
    medidasExtendida: 'El país lidera proyectos de captura directa de carbono, mantiene matriz eléctrica renovable casi total y promueve combustibles limpios para transporte marítimo y terrestre.',
    imgDefecto: 'https://gti.images.tshiftcdn.com/9281960/x/0/top-15-things-to-do-amp-places-to-visit-in-iceland-2.jpg?ixlib=php-3.3.0&w=883',
    imgCatastrofe: 'https://static.euronews.com/articles/stories/08/42/58/80/1200x675_cmsv2_83b25cf2-9736-5b95-a2be-98ebd65719f4-8425880.jpg',
    imgEcologia: 'https://www.energias-renovables.com/ficheroenergias/fotos/eolica/ampliada/w/wweawoolnorth.jpg',
  },

  'New Zealand': {
    status: 'NEUTRAL',
    color: '#ffcc00',
    descHover: 'Emisiones moderadas con metas climáticas.',
    descGeneral: 'Nueva Zelanda tiene emisiones relevantes del sector agrícola pero avanza hacia la neutralidad.',
    prediccion: 'Sin cambios en agricultura, las emisiones seguirán moderadas.',
    prediccionExtendida: 'El principal desafío de Nueva Zelanda es reducir el metano agrícola. Si logra innovaciones en ganadería y mantiene su transición energética, podría acercarse a la neutralidad en las próximas décadas.',
    medidas: 'Ley de carbono cero y expansión renovable.',
    medidasExtendida: 'El país aplica la Zero Carbon Act, impulsa energías renovables, investigación en reducción de metano ganadero y electrificación del transporte, aunque el sector agrícola sigue siendo el mayor reto.',
    imgDefecto: 'https://ichef.bbci.co.uk/ace/ws/640/amz/worldservice/live/assets/images/2015/08/10/150810123417_bandera_nueva_zelanda_624x351_jamesgray.jpg.webp',
    imgCatastrofe: 'https://www.fedeleche.cl/ww5/images/NOTICIAS/2022/n_20220928_0901.jpg',
    imgEcologia: 'https://www.ecoportal.net/wp-content/uploads/2019/11/636924680840468249_1.jpg_219914347.jpg',
  },
};